name: iOS Build

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-27

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        working-directory: circle_tracker

        run: |
          xcodebuild \
            -project CircleTrackerApp.xcodeproj \
            -scheme CircleTrackerApp \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            build
